export default {
  "foreground": "var(off_white)",
  "background": "var(ocean)",
  "caret": "var(orange)",
  // "line_highlight": "var(blue2)",
  // "selection": "var(blue2)",
  // "selection_border": "var(blue4)",
  // "inactive_selection": "var(blue2)",
  "misspelling": "var(red)",
  "shadow": "color(var(ocean_dark) alpha(0.25))",
  "active_guide": "var(grey)",
  "stack_guide": "color(var(grey) alpha(0.5))",
  "highlight": "var(grey)",
  "find_highlight_foreground": "var(grey)",
  "find_highlight": "var(yellow)",
  "brackets_options": "underline",
  "brackets_foreground": "var(orange)",
  "bracket_contents_options": "underline",
  "bracket_contents_foreground": "var(grey)",
  "tags_options": "stippled_underline",
  "tags_foreground": "var(magenta)"
}
